version: '2.3'
services:
  ryan_pytorch:
    image:
      ryan_tensorflow_gpu:latest
    runtime:
      nvidia
    volumes:
      - "/media/ryan/Data1/zData/Dataset/data_for_DSN_256:/root/Data"
      - "/tmp:/tmp"
    # ports:
    #   - "22:22"
    shm_size:
      '10gb'
    # environment:
    #   - NVIDIA_VISIBLE_DEVICES=all
    # command:
    #   nvidia-smi